### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mtc-20** [hsrwrobotics/niryo_one_ros#11] opened 2021-08-11 20:10 UTC
The [`general_message_pkgs` from Jennifer Beuhler](https://github.com/JenniferBuehler/general-message-pkgs.git) packages is a required dependency for the [gazebo_grasp plugin](/hsrwrobotics/niryo_one_ros/tree/gazebo_plugin_feat_mt20)

- [ ] Or more specifically, only `object_msgs`
- [ ] Also look into properly citing works

**Comment by hsrwrobotics** [comment] 2021-08-12 08:34
- Seems `object_msgs` is not a required dependency in ROS Melodic
  - I am not able to reproduce the missing object_msgs error when rebuilding catkin workspace
  - Attaching below a screenshot of the `catkin REQUIRED COMPONENTS` of `gaebo_graso_plugin` from my system
    ![Screenshot of catkin required](https://user-images.githubusercontent.com/56743116/129165278-134197b6-de9c-4db4-a395-8ca23d7c5ff1.png)

- So probably is required for older versions of Gazebo (?)

**Comment by hsrwrobotics** [comment] 2021-08-12 12:53
My bad, was checking the wrong workspace. `object_msgs` is not required currently.

Closing

**Closed** 2021-08-12 12:54 UTC
